-- ============================================================
-- AI Shelf — Supabase Schema
-- Run this in: Dashboard → SQL Editor → New query
-- ============================================================

-- 1. Resources table (public read)
create table if not exists resources (
  id          text primary key,
  title       text not null,
  url         text not null,
  type        text not null check (type in ('article', 'video')),
  category    text not null,
  tags        jsonb not null default '[]',
  description text not null,
  takeaways   jsonb not null default '[]',
  added_at    date not null
);

-- 2. User progress table (per-user, private)
create table if not exists user_progress (
  user_id     uuid references auth.users(id) on delete cascade,
  resource_id text references resources(id) on delete cascade,
  status      text check (status in ('unread', 'in-progress', 'read')) default 'unread',
  rating      int  check (rating between 1 and 5),
  updated_at  timestamptz default now(),
  primary key (user_id, resource_id)
);

-- 3. Row Level Security
alter table resources     enable row level security;
alter table user_progress enable row level security;

-- resources: anyone can read
create policy "resources_public_read" on resources
  for select using (true);

-- user_progress: users can only access their own rows
create policy "progress_select" on user_progress
  for select using (auth.uid() = user_id);

create policy "progress_insert" on user_progress
  for insert with check (auth.uid() = user_id);

create policy "progress_update" on user_progress
  for update using (auth.uid() = user_id);

create policy "progress_delete" on user_progress
  for delete using (auth.uid() = user_id);

-- 4. Seed resources
insert into resources (id, title, url, type, category, tags, description, takeaways, added_at) values
  ('ai-evolution-express-llm-to-agents', 'The AI Evolution Express: From LLMs to Autonomous Agents', 'https://x.com/pvergadia/status/2025390082996224079', 'article', 'AI Engineering & Education', '["llm","agents","rag","mental model","foundations"]'::jsonb, 'Visual thread charting AI evolution as five stops on a train — from zero-shot prompting to true agent architecture with loops, memory, and tool use. Clean mental model for explaining ''why agents now?''', '["Stop 1: Simple LLM → Stop 2: Document stuffing → Stop 3: RAG + Tools → Stop 4: Multi-modal → Stop 5: True Agent Architecture","Each evolution stage builds on the previous — you can''t skip to agents without understanding RAG and tools first","Use this framework to identify which ''stop'' your current AI system is at before designing the next iteration","Useful for onboarding non-technical stakeholders to agentic AI concepts without jargon"]'::jsonb, '2026-03-10'),
  ('paperclip-company-run-by-agents', 'Paperclip — How to Build a Company Run Entirely by AI Agents', 'https://x.com/roundtablespace/status/2030595632998580328', 'article', 'AI Agents & Orchestration', '["orchestration","agents","autonomy","multi-agent","cost control","audit"]'::jsonb, 'Overview of Paperclip, an open-source tool that structures AI agents into a company hierarchy with org charts, budgets, audit logs, and heartbeat scheduling. Signals the shift from individual AI tools to full AI-run companies.', '["Paperclip solves the ''20 Claude Code tabs'' chaos problem — one dashboard, full coordination and traceability","Monthly budgets per agent with automatic pause at 100% spend prevent runaway API costs","Heartbeats wake agents on a schedule to check tasks and act without human babysitting","Full audit trail: every decision, tool call, and conversation is logged immutably"]'::jsonb, '2026-03-15'),
  ('claude-obsidian-memory-stack', 'Claude + Obsidian: The Memory Stack That Compounds', 'https://x.com/nyk_builderz/status/2030904887186514336', 'article', 'Claude Workflow & Skills', '["obsidian","memory","context","Claude","workflow","teams"]'::jsonb, 'Nyk''s guide to solving Claude''s context drift problem by wiring a three-tier Obsidian memory system — enabling sessions to compound instead of reset. Includes a full runbook, config files, and checklist.', '["Teams lose 30–40 minutes per Claude session re-explaining prior context — roughly a full workday per week","The real failure is not reasoning quality; it''s drift — AI starts from zero each session","Three-tier memory system enables capture → structure → retrieve → compound","Skills and context files in Obsidian act as persistent memory injected at the start of each session"]'::jsonb, '2026-03-15'),
  ('akshay-pachaar-ai-engineering-hub', 'Akshay Pachaar: AI Engineering Roadmap + Open-Source Hub', 'https://x.com/akshay_pachaar/status/2031021906254766128', 'article', 'AI Engineering & Education', '["roadmap","agents","rag","llm","open source","curriculum","skill graphs"]'::jsonb, 'Sr. AI Engineer at Lightning AI shares a 10K+ star GitHub hub with 90+ hands-on projects covering the full AI stack, plus a thread on Skill Graphs as a superior alternative to flat SKILL.md files.', '["Skill Graphs (hierarchical, modular skills) outperform flat SKILL.md files — Claude navigates them like a senior engineer navigates a codebase","The AI Engineering Hub covers the full production stack: LLMs + RAG + Agents + Memory + Eval + LLMOps","nanobot is an intentionally minimal personal AI assistant: ~4,000 lines, works with any LLM provider","A clean, readable codebase is a feature — not a limitation — for learning and customization"]'::jsonb, '2026-03-15'),
  ('tom-doerr-ai-project-tracker', 'Tom Dörr: Daily Open-Source AI Project Tracker', 'https://x.com/tom_doerr/status/2031329821372883171', 'article', 'Curation & Discovery', '["open source","curation","discovery","agents","tools","daily"]'::jsonb, 'Tom Dörr posts open-source AI projects daily, covering agent frameworks, DSPy tools, coding agents, and local LLMs. His MAGI//ARCHIVE site aggregates discovered frontier repositories.', '["Curation is a competitive advantage when open-source AI projects are released at an overwhelming daily volume","The MAGI//ARCHIVE site provides a searchable map of frontier repos updated daily","Follow as a discovery layer, not a learning resource — high signal breadth, low per-post depth by design","His own GitHub (tom-doerr) includes original tools: ZSH + Codex plugin, Vim AI completion, Ollama-OCR"]'::jsonb, '2026-03-15'),
  ('ruben-hassid-claude-cowork-setup', 'Ruben Hassid: Claude + Cowork Personal AI Setup Guide', 'https://x.com/rubenhassid/status/2031666815554736227', 'article', 'Claude Workflow & Skills', '["Claude","workflow","context","setup","cowork","productivity","prompting"]'::jsonb, 'Practical guide to building a personal Claude-Work folder with three key context files — turning Claude''s Cowork mode into a persistent AI operating system accessible to non-developers.', '["Three key context files: about-me.md (daily workflow), my-voice.md (tone & style), my-rules.md (task constraints)","Writing my-voice.md as a style guide prevents Claude from overriding your tone in generated content","Framing Claude as a ''brutally honest thinking partner'' via a custom system prompt dramatically improves output quality","Start sessions with: ''DO NOT start yet. Ask me clarifying questions so we can align step by step.''"]'::jsonb, '2026-03-15'),
  ('vmlops-llmops-production', '_vmlops: MLOps / LLMOps Production Insights', 'https://x.com/_vmlops/status/2032355826665734509', 'article', 'AI Engineering & Education', '["llmops","mlops","production","prompt versioning","cost","non-determinism"]'::jsonb, 'Account focused on LLMOps practices — covering non-determinism management, prompt versioning as software engineering, and cost control for token-heavy production systems.', '["LLMOps is a distinct discipline from traditional MLOps — non-determinism, context windows, and prompt versioning require different practices","Production LLM systems are complex orchestrations: foundation models + retrieval + guardrails + routing + feedback loops","Prompt engineering is now software engineering — prompts require versioning, testing, and CI/CD pipelines","Cost is first-class: token counting, caching strategies, and model selection directly impact product margins"]'::jsonb, '2026-03-20'),
  ('gitnexus-knowledge-graph-codebase', 'GitNexus: A Knowledge Graph for Your Codebase', 'https://x.com/pvergadia/status/2033403840264126816', 'article', 'AI Agents & Orchestration', '["codebase","agents","blast radius","MCP","open source","safety","dependency graph"]'::jsonb, 'GitNexus builds a full knowledge graph of your codebase — mapping dependencies, call chains, and execution flows — so AI coding agents know what they might break before they act.', '["AI agents are the smartest coders on your team — and they have no awareness of blast radius","GitNexus provides blast radius analysis before any change, coordinated symbol renaming across 5+ files, and an auto-generated codebase wiki","Plugs into Claude Code, Cursor, and Windsurf via MCP: npx gitnexus analyze","Pre-indexing before a session starts is key — live graph queries during agent work add latency"]'::jsonb, '2026-03-20'),
  ('lessons-building-claude-code', 'Lessons from Building Claude Code: How We Use Skills', 'https://x.com/trq212/status/2033949937936085378', 'article', 'Claude Workflow & Skills', '["skills system","Claude Code","agents","progressive disclosure","anthropic"]'::jsonb, 'In-depth thread from a core Claude Code engineer at Anthropic on how Skills actually work internally — folder-based structures with progressive disclosure, Gotchas sections, and trigger descriptions. 6M+ views.', '["A Skill is a folder, not just a text file — it can include scripts, reference code, assets, and a Gotchas section that evolves over time","Skill descriptions must be written as trigger conditions, not summaries, or Claude won''t fire them at the right moment","Progressive disclosure: Claude reads skill metadata first (~100 tokens), then dives deeper only when needed","The highest-signal section in any skill is the Gotchas — built up from real failure points, not anticipated ones"]'::jsonb, '2026-03-20'),
  ('complete-ai-stack-2026', 'The Complete AI Stack for 2026 (48 Tools)', 'https://x.com/bharukashraddha/status/2034219375197307323', 'article', 'Tools & Stacks', '["tools","stack","overview","2026","agents","coding","research"]'::jsonb, 'Curated thread listing 48 AI tools organized into a coherent stack for 2026, spanning chatbots, video/image generation, coding assistants, AI agents, voice tools, and research utilities.', '["A curated stack beats a random collection — grouping by function reveals gaps and redundancies in your AI workflow","The agent layer (Claude Computer Use, Operator, Manus AI) is now a distinct category alongside chatbots","Most teams underinvest in evaluation and research tools — Elicit, Consensus, and Perplexity deserve their own category","Coding assistants like Windsurf, Bolt.new, and Lovable now enable full app creation without traditional dev environments"]'::jsonb, '2026-03-25'),
  ('karpathy-llm-wiki-pattern', 'Karpathy: LLM Wiki — A Pattern for Persistent Knowledge Bases', 'https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f', 'article', 'AI Engineering & Education', '["llm","knowledge management","rag","wiki","architecture","karpathy"]'::jsonb, 'Andrej Karpathy''s architectural pattern for building a personal knowledge base that LLMs actively maintain — a compounding wiki rather than a search index. The foundational pattern behind persistent AI memory systems.', '["RAG retrieves knowledge anew each time; LLM Wiki compiles it once and keeps it current — it''s a compounding artifact, not a search index","Three layers: raw sources (immutable), wiki (LLM writes and maintains), schema (CLAUDE.md — tells LLM how to run the wiki)","Three operations: Ingest (read + update 10-15 wiki pages), Query (answer against wiki), Lint (find contradictions, orphans, gaps)","LLM solves the core reason people abandon wikis: not reading and thinking — but bookkeeping. It can touch 15 files in one pass without fatigue"]'::jsonb, '2026-04-08'),
  ('claude-code-best-practice-reference', 'claude-code-best-practice: The Definitive Claude Code Reference', 'https://github.com/shanraisshan/claude-code-best-practice', 'article', 'Claude Workflow & Skills', '["Claude Code","best practices","agents","skills","subagents","hooks","MCP"]'::jsonb, 'The most comprehensive collection of Claude Code best practices — 69 tips from Boris Cherny and the Anthropic team, covering all primitives: Subagents, Commands, Skills, Hooks, and MCP. 35K+ GitHub stars.', '["Three building blocks: Subagents (isolated context, autonomous actor), Commands (inject knowledge into current context), Skills (customizable, preloadable with progressive disclosure)","Orchestration pattern: Command → Agent → Skill — the standard architecture for complex agentic workflows","Keep CLAUDE.md under 200 lines; rules in settings.json are enforced more strictly than rules in CLAUDE.md","Context is the main resource: /compact at 50% fill, /clear on task switch, subagents for isolating intermediate work"]'::jsonb, '2026-04-10'),
  ('ai-engineering-roadmap-ronin', 'AI Engineering Roadmap — 6-Month Learning Path', 'https://x.com/deronin_/status/2042875513492947286', 'article', 'AI Engineering & Education', '["roadmap","ai engineering","llm","industry","learning path"]'::jsonb, 'Tweet linking to a structured 6-month AI Engineering roadmap covering LLM APIs, RAG, agents, and deployment. Treat the alarmist framing critically — the value is in the practical learning path.', '["AI Engineering is not ML — it''s working with ready models via API: pipelines, RAG, agents, orchestration. Closer to frontend work than classical ML","The linked March 2026 roadmap covers the full AI Engineering stack across ~6 months of structured study","Dario Amodei''s automation claims are real context but the ''two types of people'' framing is marketing — evaluate the roadmap on its own merits","Key competencies: LLM API usage, RAG pipeline design, agent orchestration, evaluation, and deployment"]'::jsonb, '2026-04-13'),
  ('google-engineer-80-percent-automation', 'Google Engineer Automated 80% of His Work with Claude Code', 'https://x.com/noisyb0y1/status/2043609541477044439', 'article', 'Claude Workflow & Skills', '["Claude Code","automation","workflow","productivity","agents","case study"]'::jsonb, 'Case study of an 11-year Google engineer who automated ~80% of his daily work with Claude Code and a custom .NET orchestrator, reducing his workday to 2–3 hours. Shows the gap between occasional and systematic AI use.', '["The automation works because of domain expertise, not AI magic — 11 years of experience enables precise task formulation and critical result review","A custom .NET orchestrator sits between the engineer and Claude Code — structure and context management is the key differentiator","This is the human-in-the-loop agent pattern: human sets goal and criteria, agent executes, human validates","The gap between ''using Claude occasionally'' and ''embedding the agent into your workflow'' yields a multiplicative, not marginal, productivity gain"]'::jsonb, '2026-04-13'),
  ('karpathy-inspired-claude-code-guidelines', 'Karpathy-Inspired Claude Code Guidelines (CLAUDE.md)', 'https://github.com/forrestchang/andrej-karpathy-skills', 'article', 'Claude Workflow & Skills', '["Claude Code","CLAUDE.md","best practices","karpathy","prompt engineering","simplicity"]'::jsonb, 'A single CLAUDE.md file distilling Karpathy''s four principles for working with Claude Code — directly addressing the four core LLM failure modes in coding tasks. Copy into any project immediately.', '["Think Before Coding: if a task is ambiguous, name it explicitly and ask — don''t silently pick an interpretation","Simplicity First: minimum code that solves the problem; no abstractions ''for the future'' that weren''t requested","Surgical Changes: only touch what directly relates to the request; every changed line must trace to a specific user ask","LLMs are exceptionally good at looping until they meet specific goals — formulate success criteria, not step-by-step instructions"]'::jsonb, '2026-04-13'),
  ('obsidian-seed-claude-thinking-partner', 'Obsidian Seed: Claude Code as a Persistent Thinking Partner', 'https://github.com/dkushnikov/obsidian-seed', 'article', 'Claude Workflow & Skills', '["obsidian","Claude Code","memory","context","workflow","productivity","session management"]'::jsonb, 'Wizard-driven methodology for turning Claude Code into a context-aware thinking partner by wiring an Obsidian vault with persistent session memory. Solves the ''smart stranger'' problem — every session starting from zero.', '["The model is not the bottleneck — context is. A system that loads your context at every session compounds in value over months","The stateful multiplier has five components that only work well together: CLAUDE.md, MEMORY.md, session logs, TODO with age markers, and session workflow rules","For episodic users (vault opened once a week): a 5-minute brain-dump note before any complex session prevents stale-context failures","The session close is the highest-leverage habit — skip it and compound interest breaks. Most users fail here, not at setup"]'::jsonb, '2026-04-13'),
  ('production-ai-architecture-9-layer', 'Production AI Architecture — 9-Layer Breakdown', 'https://x.com/technmak/status/2042951175071502513', 'article', 'AI Engineering & Education', '["architecture","rag","agents","production","services","semantic cache"]'::jsonb, 'Thread breaking down a real production AI application into 9 layers — showing what a mature RAG + agent stack looks like beyond toy examples, with concrete folder structures and component logic.', '["Production AI splits into services/ (RAG pipeline, semantic cache, memory, query rewriter, router) and agents/ (document grader, decomposer, adaptive router)","services/ is stateless utilities; agents/ is orchestrators with decision logic — this separation is the key architectural pattern","Semantic cache prevents repeated similar queries from hitting the LLM — a first-class performance and cost primitive, not an optimization","The system self-corrects: if the document grader finds insufficient relevance, the search restarts with modified parameters — this is the agentic loop in practice"]'::jsonb, '2026-04-13'),
  ('mdancho84-regression-diagnostics-visual', '6 Diagnostic Checks for Validating Regression Models (Visual)', 'https://x.com/mdancho84/status/2046974114091389052', 'article', 'AI Engineering & Education', '["ml-fundamentals","regression","diagnostics","visualization","data science"]'::jsonb, 'Matt Dancho (@mdancho84, Business Science) shares a visual breakdown of 6 essential diagnostic checks for validating regression models — a practical reference for any data scientist or ML practitioner building predictive models.', '["Regression validation is not optional — skipping diagnostics leads to models that look good on paper but fail in production","The 6 checks cover residual analysis, linearity, homoscedasticity, normality, multicollinearity, and influential points — each targets a specific assumption the model makes","Visual diagnostics (residual plots, Q-Q plots, leverage plots) are faster to interpret than statistical tests alone and catch issues that metrics miss","Business Science''s style: data science education paired with R/Python examples aimed at practitioners, not researchers"]'::jsonb, '2026-04-24'),
  ('dailydoseofds-agent-memory-3-layer', 'The Agent Memory Trick Top AI Labs Use — 3-Layer Architecture', 'https://x.com/dailydoseofds_/status/2046503454919864735', 'article', 'AI Agents & Orchestration', '["agents","memory","rag","knowledge graph","embeddings","cognee"]'::jsonb, 'Daily Dose of Data Science (Avi Chawla) explains why single vector-store memory fails at multi-hop reasoning and how Microsoft, Google, and Meta use a complementary 3-layer memory stack — relational + vector + graph — to build agents that reason over connected facts.', '["Storing more data in a vector DB doesn''t improve reasoning — it only retrieves semantically similar facts, missing intermediate connections needed for multi-hop questions","The 3-layer stack: relational layer (provenance, timestamps, permissions) + vector layer (semantic search) + graph layer (relationship mapping) — each layer solves what the others can''t","Cognee is an open-source ECL pipeline (Extract, Cognify, Load) that populates all three stores simultaneously during indexing, not post-hoc","Context windows have a ''lost in the middle'' problem — accuracy drops 30%+ when relevant facts are buried deep in a long prompt; structured memory is the fix"]'::jsonb, '2026-04-24'),
  ('avichawla-claude-code-token-28x', 'How to Cut Claude Code Token Usage 2.8x via Backend Architecture', 'https://x.com/_avichawla/status/2046500537584218438', 'article', 'Claude Workflow & Skills', '["Claude Code","token optimization","agents","backend design","cost","skills"]'::jsonb, 'Avi Chawla demonstrates that Claude Code token consumption is primarily an architectural problem, not a model problem — and shows how three backend changes reduced a DocuRAG build from 10.4M tokens ($9.21) to 3.7M tokens ($2.81) with zero errors.', '["Better models cost more tokens when the backend is poorly structured — more capable models spend more reasoning filling knowledge gaps from ambiguous APIs","Three fixes: (1) pre-load domain patterns as Skills so Claude doesn''t rediscover them via trial-and-error; (2) use structured CLI with JSON + semantic exit codes, not ambiguous error messages; (3) provide unified state inspection instead of multiple fragmented metadata calls","The 2.8x reduction came from eliminating error-retry loops, not from prompt tuning — architectural clarity is the highest-leverage optimization","Benchmark: Supabase approach = 10.4M tokens, 12 messages, 8 debugging cycles; InsForge approach = 3.7M tokens, 1 message, zero errors — same end result"]'::jsonb, '2026-04-24'),
  ('avichawla-diffusion-llms-anatomy', 'The Anatomy of Diffusion LLMs — A Fundamentally Different Way to Generate Text', 'https://x.com/_avichawla/status/2044670188998803855', 'article', 'AI Engineering & Education', '["architecture","llm","diffusion","inference","ml-fundamentals","gpu"]'::jsonb, 'Avi Chawla explains diffusion language models from scratch — how they generate all tokens in parallel by progressively unmasking a sequence, why this is fundamentally more GPU-efficient than left-to-right autoregressive decoding, and which emerging models already match GPT-4-class performance.', '["Every current production LLM (GPT-4, Claude, Gemini) generates one token at a time left-to-right, yielding ~1 FLOP per byte on hardware designed for 100+ FLOPs/byte — a massive hardware mismatch","Diffusion LLMs start with a fully masked sequence and unmask all tokens in parallel using bidirectional attention, shifting inference from memory-bandwidth-bound to compute-bound — matching GPU strengths","Emerging diffusion models (BD3-LM, LLaDA 8B, Dream 7B) already match or exceed autoregressive benchmarks — this is no longer a research curiosity","Understanding the math (ELBO-derived training objective, forward/reverse masking, block-level KV caching) will become a practical competency as these models enter production"]'::jsonb, '2026-04-24'),
  ('dkushnikov-claude-code-mcp-plugin', 'Building a Claude Code Plugin with MCP Server — Real-World Example', 'https://github.com/dkushnikov/plaud-pipeline', 'article', 'Claude Workflow & Skills', '["mcp","claude-code","python","tools","agents","fastmcp"]'::jsonb, 'Case study: an engineer built and published a Claude Code plugin with an MCP server in a single session, wrapping a third-party voice recorder API. Shows the real workflow, stack, and patterns — useful as a template for any similar project.', '["MCP server on FastMCP (Python) + stdio transport = ~200 lines of code for 7 tools. No HTTP server needed — Claude Code launches the process itself on session start","One plugin replaced ~500 lines of scattered bash/Python scripts — a dramatic complexity reduction","Business logic for classification is in a YAML config: no hardcoded rules, easy to change behavior without touching code","Multi-model review council (3 frontier models review the design before implementation) caught a frontmatter parsing bug and a name collision before they became problems","The pattern ''MCP server as a wrapper over any API'' can be reproduced in a few hours and integrates natively into Claude"]'::jsonb, '2026-04-09')
on conflict (id) do nothing;
